export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

export const GET_FILTER_PRODUCTS_REQUEST = "GET_FILTER_PRODUCTS_REQUEST";
export const GET_FILTER_PRODUCTS_SUCCESS = "GET_FILTER_PRODUCTS_SUCCESS";
export const GET_FILTER_PRODUCTS_FAILURE = "GET_FILTER_PRODUCTS_FAILURE";

export const GET_PRODUCTS_DETAILS_REQUEST = "GET_PRODUCTS_DETAILS_REQUEST";
export const GET_PRODUCTS_DETAILS_SUCCESS = "GET_PRODUCTS_DETAILS_SUCCESS";
export const GET_PRODUCTS_DETAILS_FAILURE = "GET_PRODUCTS_DETAILS_FAILURE";

export const SORTED_BY_PRICE_REQUEST = "SORTED_BY_PRICE_REQUEST";
export const SORTED_BY_PRICE_SUCCESS = "SORTED_BY_PRICE_SUCCESS";
export const SORTED_BY_PRICE_FAILURE = "SORTED_BY_PRICE_FAILURE";

export const SORTED_BY_DISCOUNT_REQUEST = "SORTED_BY_DISCOUNT_REQUEST";
export const SORTED_BY_DISCOUNT_SUCCESS = "SORTED_BY_DISCOUNT_SUCCESS";
export const SORTED_BY_DISCOUNT_FAILURE = "SORTED_BY_DISCOUNT_FAILURE";

export const SORTED_BY_RATING_REQUEST = "SORTED_BY_RATING_REQUEST";
export const SORTED_BY_RATING_SUCCESS = "SORTED_BY_RATING_SUCCESS";
export const SORTED_BY_RATING_FAILURE = "SORTED_BY_RATING_FAILURE";
