export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAILURE = "USER_SIGNUP_FAILURE";

export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";

export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_ADDRESS_REQUEST = "USER_ADDRESS_REQUEST";
export const USER_ADDRESS_FAILURE = "USER_ADDRESS_FAILURE";
export const USER_ADDRESS_SUCCESS = "USER_ADDRESS_SUCCESS";
